### ISSUE TITLE
Installation on Fedora 28 fails

### ISSUE THREAD

**Issue by FunkyFr3sh** [mmtrt/cncra#1]
The window where you can select Full Game / Multiplayer pops up, after the selection you get the following errors:

```
cp: cannot stat '/tmp/RedAlert1_Online': No such file or directory
rm: cannot remove '/tmp/RedAlert1_Online': No such file or directory
wine: cannot find ''
```

**Comment by mmtrt** [comment]
I'm not having such errors here just retested snap installing multi working fine so maybe terminal shell is different then bash or maybe game is not installing in /tmp when setup installs it?

**Comment by FunkyFr3sh** [comment]
I think it's not even downloading the installer. Both full game and multiplayer don't work.

Can't test atm, just wanted to create the issue so the problem is known
