### ISSUE TITLE
Unable to load since update

### ISSUE THREAD

**Issue by premonut** [mmtrt/cncra#4]
I am running Ubuntu 18.04.1 LTS 32bit at the moment. A few days ago I did a massive update on the PC and since then  cncra or cnctsun wont load at all. I removed cncra and re-installed cncra with no improvement. Im newish to Ubuntu and Linux, do you have any recommendations? might it be the 32bit processor?

BTW. Thank you very much for the hardwork. I use to play this when it first came out and I am enjoying playing C&C conquer again. 

**update**
I have a 64bit  tower. So ill install the 64bit version and try again. 

**update#2** ubuntu re-install to 64bit seems to be working. Im not sure how to delete this issue....

**Comment by mmtrt** [comment]
That 32 bit issue could be of `wine-platform` snap migration which snaps having removed support for `wine-platform-i386` on recent updates, if you had run snap command on 32bit distro could have shown you the needed instructions to fix it. Anyway glad your issue is solved
`snap run cncra`
