### ISSUE TITLE
cnc snaps run on all cpus which is leading to disappearing mouse cursor bug

### ISSUE THREAD

**Issue by FunkyFr3sh** [mmtrt/cncra#5]
Is it possible to run all cnc snaps on a single cpu?

In the cncnet packages it is done like this:
`taskset -c 0 wine "$LAUNCHER"`

Normally this shouldn't be a problem in newer wine versions since the games call "SetProcessAffinityMask(GetCurrentProcess(), 1);". However, this doesn't seem to work in snaps (Maybe because of the strict confinement?).

Old games generally have problems with that, the cnc games end up with a invisible cursor at some point (There can be random crashes too).

**Comment by mmtrt** [comment]
I don't know how to test this as I'm not seeing this issue on my systems. Also don't know if taskset is working or not with current changes.

**Comment by FunkyFr3sh** [comment]
Testing the bug itself can be difficult, might be possible to play 1hour and then it happens or could happen in 10 minutes. You can start a skirmish game and then use taskset to check the affinity.

`taskset -p <PID>`

It should return 1

**Comment by mmtrt** [comment]
thanks just confirming that taskset is working. I'll add changes to `cnctsun` `cncra2yr`
```
14654 mmtrt     20   0 2879436 105872  51788 S  24.6  1.3   0:04.27 ra95-spawn.exe

pid 14654's current affinity mask: 1
pid 14654's current affinity list: 0
```

**Comment by FunkyFr3sh** [comment]
Looks good, I also just tested it quick with cncra snap on edge channel and it works for me too. Not sure if there will be any differences between edge and stable channel (Are both using strict confinement?).

**Comment by mmtrt** [comment]
yes both have `strict` anyway I'll push edge build to `stable` now. Build server pushes the builds to edge branch only.
