### ISSUE TITLE
[Feature request] Add support for easy language switching

### ISSUE THREAD

**Issue by SoulInfernoDE** [mmtrt/cncra#6]
Hi mmtrt,
is it possible to use the newest RA1installer from the cncnet source as this installer lets you choose the language pack before installation. (Don't execute the RA1installer in silent mode)

- [RA1installer.exe](http://downloads.cncnet.org/RA1installer.exe) [NEW with language packs added]

with best regards

Soul Inferno

**Comment by mmtrt** [comment]
Removed silent flag 4 days ago.

**Comment by SoulInfernoDE** [comment]
Thanks, will test it.
I really like your snaps. :-)

Works like a charm. Thanks @mmtrt :1st_place_medal:
