### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by cacfd3a** [mmtrt/cncra#7]
This used to run fine. All of a sudden, I get the following error:

```~$ snap run cncra
/snap/cncra/54/bin/sommelier: line 119:  5788 Segmentation fault      (core dumped) env WINEARCH="${WINEARCH}" WINEPREFIX="${WINEPREFIX}" taskset -c 0 "${WINELOADER}" "${WINE_EXE}"
```

Same for tibsun. What can I do?

**Comment by mmtrt** [comment]
did you tried reinstalling the snaps.

can you post info of

`snap interfaces cncra`

also post info of 

`snap info wine-platform | grep installed`

**Comment by cacfd3a** [comment]
Seems to be a bug related to Wine / sommelier. After a while, all my attempt to open the launcher opened at once. Will post the logs when I get behind my computer again.

**Comment by BrancolinoX** [comment]
Maybe wine issues as TMNationsForever is failing on install also with same errors.

**Comment by cacfd3a** [comment]
Output:

```Slot                            Plug
:desktop                        cncra
:desktop-legacy                 cncra
:home                           cncra
:network                        cncra
:network-bind                   cncra
:opengl                         cncra
:pulseaudio                     cncra
:wayland                        cncra
:x11                            cncra
gtk-common-themes:icon-themes   cncra
wine-platform:wine-base-stable  cncra:wine-platform-plug
-                               cncra:hardware-observe
-                               cncra:joystick
-                               cncra:process-control
```

```
$snap info wine-platform | grep installed

installed:   3.0.4-4.0            (111) 461MB
```


I have noticed that the Tiberian Sun Launcher was slow to open and feared it might be crashing as well; the solution seems to be to just wait. Maybe some async io thing Wine... Who knows.
